# Pruning Basics in PyTorch

In [1]:
import torch
from torch import nn
from torch.nn.utils import prune

### Let us first create a tensor

In [2]:
module = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)
module

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [3]:
module.weight

Parameter containing:
tensor([[[[ 0.3094,  0.1524,  0.2887],
          [-0.3017,  0.0797,  0.0339],
          [ 0.0440, -0.3210, -0.0181]]]], requires_grad=True)

## Attributes of the created Tensor

In [4]:
list(module.named_parameters())

[('weight',
  Parameter containing:
  tensor([[[[ 0.3094,  0.1524,  0.2887],
            [-0.3017,  0.0797,  0.0339],
            [ 0.0440, -0.3210, -0.0181]]]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([-0.0424], requires_grad=True))]

In [5]:
list(module.named_buffers())

[]

In [6]:
module._forward_pre_hooks

OrderedDict()

## Prune 30% of the weights

In [7]:
prune.l1_unstructured(module, name="weight", amount=0.33)

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

## Attributes after Pruning

In [8]:
list(module.named_parameters())

[('bias',
  Parameter containing:
  tensor([-0.0424], requires_grad=True)),
 ('weight_orig',
  Parameter containing:
  tensor([[[[ 0.3094,  0.1524,  0.2887],
            [-0.3017,  0.0797,  0.0339],
            [ 0.0440, -0.3210, -0.0181]]]], requires_grad=True))]

In [9]:
list(module.named_buffers())

[('weight_mask',
  tensor([[[[1., 1., 1.],
            [1., 1., 0.],
            [0., 1., 0.]]]]))]

In [10]:
module.weight

tensor([[[[ 0.3094,  0.1524,  0.2887],
          [-0.3017,  0.0797,  0.0000],
          [ 0.0000, -0.3210, -0.0000]]]], grad_fn=<MulBackward0>)

In [11]:
module._forward_pre_hooks

OrderedDict([(0, <torch.nn.utils.prune.L1Unstructured at 0x7fe094dca590>)])

## Making the pruning permanent

In [12]:
prune.remove(module, name="weight")

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [13]:
list(module.named_parameters())

[('bias',
  Parameter containing:
  tensor([-0.0424], requires_grad=True)),
 ('weight',
  Parameter containing:
  tensor([[[[ 0.3094,  0.1524,  0.2887],
            [-0.3017,  0.0797,  0.0000],
            [ 0.0000, -0.3210, -0.0000]]]], requires_grad=True))]

In [14]:
module._forward_pre_hooks

OrderedDict()

In [15]:
list(module.named_buffers())

[]